// One command to set up a new Ashrium client on their own Shopify app.
//
//   npm run client:new -- <slug> <shop>.myshopify.com <owner-email> "<Company name>"
//
// Run it in your own terminal (it opens Shopify sign-in and asks questions).
// Every step is checked; if one fails the command stops with the fix and
// nothing in Ashrium is half-created. Re-running with the same slug is safe.
import { execSync, spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { createInterface } from 'node:readline/promises';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SHOPIFY = process.env.SHOPIFY_CLI ?? 'npx --yes @shopify/cli@3';
const SCOPES = 'read_products,read_metaobjects';
const API_VERSION = '2026-07';

function loadEnvFile(fileName) {
  try {
    for (const rawLine of readFileSync(path.join(ROOT, fileName), 'utf8').split(/\r?\n/)) {
      const line = rawLine.trim();
      const separator = line.indexOf('=');
      if (!line || line.startsWith('#') || separator <= 0) continue;
      const key = line.slice(0, separator).trim();
      let value = line.slice(separator + 1).trim();
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      if (!process.env[key]) process.env[key] = value;
    }
  } catch {
    // Optional local env file.
  }
}

let stepNumber = 0;
function step(title) {
  stepNumber += 1;
  console.log(`\n[${stepNumber}] ${title}`);
}
function fail(message, fix) {
  console.error(`\n✗ ${message}`);
  if (fix) console.error(`  Fix: ${fix}`);
  console.error('  Nothing was created in Ashrium. Fix the problem and run the same command again.');
  process.exit(1);
}
function ok(message) {
  console.log(`  ✓ ${message}`);
}

function runInteractive(command) {
  const result = spawnSync(command, { cwd: ROOT, shell: true, stdio: 'inherit' });
  return result.status === 0;
}

function appToml({ clientId, name, appBaseUrl }) {
  return `# Generated by npm run client:new. Re-run the command instead of editing by hand.
client_id = "${clientId}"
name = "${name.replaceAll('"', "'")}"
application_url = "${appBaseUrl}/api/v1/shopify/install"
embedded = false

[access_scopes]
scopes = "${SCOPES}"
use_legacy_install_flow = false

[auth]
redirect_urls = [ "${appBaseUrl}/api/v1/shopify/oauth/callback" ]

[webhooks]
api_version = "${API_VERSION}"

  [[webhooks.subscriptions]]
  topics = [ "products/create", "products/update", "products/delete", "app/uninstalled" ]
  uri = "${appBaseUrl}/api/v1/shopify/webhooks"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "${appBaseUrl}/api/v1/shopify/webhooks"

[build]
include_config_on_deploy = true
`;
}

loadEnvFile('.env.local');
loadEnvFile('.env');

const [slug, shopInput, emailInput, ...companyParts] = process.argv.slice(2);
const companyName = companyParts.join(' ').trim();
const shopDomain = (shopInput ?? '').trim().toLowerCase().replace(/^https?:\/\//, '').replace(/\/.*$/, '');
const email = (emailInput ?? '').trim().toLowerCase();
const appBaseUrl = (process.env.APP_BASE_URL ?? 'https://www.ashrium.org').trim().replace(/\/$/, '');
const operatorSecret = process.env.ASHRIUM_OPERATOR_SECRET?.trim() ?? '';

step('Checking the details');
if (!slug || !/^[a-z0-9][a-z0-9-]{1,39}$/.test(slug)) {
  fail(
    'The first argument must be a short client name like "acme-apparel" (lowercase letters, digits, dashes).',
    'npm run client:new -- acme-apparel acme.myshopify.com owner@acme.com "Acme Apparel"',
  );
}
if (!/^[a-z0-9][a-z0-9-]*\.myshopify\.com$/.test(shopDomain)) {
  fail(`"${shopInput ?? ''}" is not a *.myshopify.com store address.`, 'Use the store\'s myshopify.com address, not its custom domain.');
}
if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
  fail(`"${emailInput ?? ''}" is not an email address.`, 'Use the store owner\'s email; it becomes their Ashrium sign-in.');
}
if (!companyName) {
  fail('The company name is missing.', 'Put it last, in quotes: "Acme Apparel".');
}
if (operatorSecret.length < 16) {
  fail('ASHRIUM_OPERATOR_SECRET is not set.', 'Add it to .env.local (the same value as on Vercel).');
}
if (!appBaseUrl.startsWith('https://')) {
  fail(`APP_BASE_URL is ${appBaseUrl}; Shopify needs the live https address.`, 'Set APP_BASE_URL=https://www.ashrium.org in .env.local.');
}
ok(`${companyName} · ${shopDomain} · ${email}`);

const configName = slug;
const tomlPath = path.join(ROOT, `shopify.app.${configName}.toml`);
const appName = `Ashrium – ${companyName}`.slice(0, 30);

step('Creating or linking the client\'s Shopify app');
if (!existsSync(tomlPath)) {
  console.log(`  Shopify will ask you to sign in, then: choose "Yes, create it as a new app" and name it "${appName}".`);
  if (!runInteractive(`${SHOPIFY} app config link --config ${configName}`)) {
    fail('Shopify CLI could not create or link the app.', 'Sign in with the Partner account that owns Ashrium\'s apps, then run the command again.');
  }
}
const linked = existsSync(tomlPath) ? readFileSync(tomlPath, 'utf8') : '';
const clientId = linked.match(/^client_id\s*=\s*"([a-f0-9]{32})"/m)?.[1];
if (!clientId) {
  fail(`shopify.app.${configName}.toml has no client_id.`, `Delete shopify.app.${configName}.toml and run the command again.`);
}
writeFileSync(tomlPath, appToml({ clientId, name: linked.match(/^name\s*=\s*"([^"]+)"/m)?.[1] ?? appName, appBaseUrl }));
ok(`App ${clientId} configured: install → ${appBaseUrl}/api/v1/shopify/install, scopes ${SCOPES}, webhooks on.`);

step('Deploying the app settings and the Try On theme block');
if (!runInteractive(`${SHOPIFY} app deploy --config ${configName} --force --message "client:new ${slug}"`)) {
  fail('Shopify did not accept the deploy.', 'Read the Shopify error above, fix it, and run the command again.');
}
ok('Deployed.');

step('Reading the app secret');
let clientSecret = '';
try {
  const envOutput = execSync(`${SHOPIFY} app env show --config ${configName}`, { cwd: ROOT, encoding: 'utf8' });
  clientSecret = envOutput.match(/SHOPIFY_API_SECRET\s*=\s*(\S+)/)?.[1] ?? '';
} catch {
  clientSecret = '';
}
if (clientSecret.length < 20) {
  fail('Could not read the app secret from Shopify CLI.', 'Run the command again; if it repeats, update Shopify CLI.');
}
ok('Secret read (it is stored encrypted in Ashrium and never printed).');

step('The one step Shopify only allows in the browser');
console.log('  1. Open https://dev.shopify.com/dashboard and open the app named');
console.log(`     "${appName}".`);
console.log('  2. Go to Distribution → Custom distribution.');
console.log(`  3. Enter ${shopDomain} and press Generate link.`);
console.log('  4. Copy the install link and paste it here.');
const prompt = createInterface({ input: process.stdin, output: process.stdout });
let installUrl = '';
for (let attempt = 0; attempt < 3 && !installUrl; attempt += 1) {
  const answer = (await prompt.question('  Install link: ')).trim();
  try {
    const url = new URL(answer);
    if (url.protocol === 'https:' && /(^|\.)shopify\.com$/i.test(url.hostname)) {
      installUrl = answer;
    } else {
      console.log('  That is not a shopify.com link. Copy the link Shopify generated.');
    }
  } catch {
    console.log('  That is not a link. Copy the link Shopify generated.');
  }
}
prompt.close();
if (!installUrl) {
  fail('No install link was given.', 'Generate it in Distribution → Custom distribution and run the command again.');
}
ok('Install link accepted.');

step('Creating the Ashrium account and sending the invite');
const response = await fetch(`${appBaseUrl}/api/v1/operator/invite-merchant`, {
  method: 'POST',
  headers: { Authorization: `Bearer ${operatorSecret}`, 'Content-Type': 'application/json' },
  body: JSON.stringify({
    email,
    companyName,
    shopifyApp: { clientId, clientSecret, shopDomain, installUrl },
  }),
});
const body = await response.text();
let payload = null;
try {
  payload = JSON.parse(body);
} catch {
  payload = null;
}
if (!response.ok) {
  fail(`Ashrium refused the new account (${response.status}): ${payload?.message ?? payload?.code ?? body.slice(0, 200)}`,
    'If the email or store is already set up, that client already exists. Otherwise fix the message above.');
}
ok(`Account created (tenant ${payload.tenantId}).`);

step('Verifying');
const probe = await fetch(`${appBaseUrl}/api/v1/shopify/install?shop=${shopDomain}`, { redirect: 'manual' });
if (probe.status === 401) {
  ok(`${shopDomain} is registered to this client (unsigned install request correctly refused).`);
} else {
  console.warn(`  ! Install endpoint answered ${probe.status} for ${shopDomain}; expected 401. Check the Vercel deploy is current.`);
}
if (payload.inviteEmailSent) {
  ok(`Invite email sent to ${email}.`);
} else {
  console.warn(`  ! Invite email NOT sent${payload.inviteEmailError ? ` (${payload.inviteEmailError})` : ''}.`);
  console.warn(`    Send this link to ${email} yourself (it works once):`);
  console.warn(`    ${payload.inviteLink}`);
}

console.log(`\nDone. ${companyName} can now:`);
console.log('  1. Open the invite and set a password.');
console.log('  2. Press Connect Shopify; Shopify asks them to approve Ashrium on their store.');
console.log('  3. Their products come in automatically.');
console.log(`\nCommit shopify.app.${configName}.toml so the next deploy keeps this client's settings.`);
